#!/usr/bin/env python3
"""Builds js/data/cities.js from GeoNames' cities15000.txt and admin1CodesASCII-derived names.

Input (not committed, download from https://download.geonames.org/export/dump/):
  cities15000.txt   cities with population > 15,000 or capitals, CC BY 4.0
  admin_codes.txt   '|'-separated 'CC.admin1' codes used by the cities (sorted)
  admin_names.txt   '|'-separated ASCII names for those codes, same order

Output rows are sorted by population, largest first, so the site's search can rank by row order.
Row fields (tab-separated): name, ascii name if it differs from the name with accents stripped,
country code, admin index, latitude, longitude, time-zone index.

Usage: python3 tools/build-cities.py <folder with the three inputs>
"""
import sys, os, json, unicodedata

src = sys.argv[1]
codes = open(os.path.join(src, 'admin_codes.txt'), encoding='utf-8').read().strip().split('|')
names = open(os.path.join(src, 'admin_names.txt'), encoding='utf-8').read().rstrip('\n').split('|')
assert len(codes) == len(names), (len(codes), len(names))
admin_name = dict(zip(codes, names))

def fold(s):
    return ''.join(c for c in unicodedata.normalize('NFD', s) if unicodedata.category(c) != 'Mn').lower()

rows = []
for line in open(os.path.join(src, 'cities15000.txt'), encoding='utf-8'):
    f = line.rstrip('\n').split('\t')
    rows.append({'name': f[1], 'ascii': f[2], 'cc': f[8], 'a1': f[8] + '.' + f[10],
                 'lat': float(f[4]), 'lon': float(f[5]), 'pop': int(f[14] or 0), 'tz': f[17]})
rows.sort(key=lambda r: -r['pop'])

tzs = sorted({r['tz'] for r in rows})
tzi = {t: i for i, t in enumerate(tzs)}
admins = sorted({admin_name.get(r['a1'], '') for r in rows})
adi = {a: i for i, a in enumerate(admins)}

out = []
for r in rows:
    asc = r['ascii'] if fold(r['name']) != r['ascii'].lower() else ''
    out.append('\t'.join([r['name'].replace('\t', ' '), asc, r['cc'], str(adi[admin_name.get(r['a1'], '')]),
                          f"{r['lat']:.4f}".rstrip('0').rstrip('.'), f"{r['lon']:.4f}".rstrip('0').rstrip('.'),
                          str(tzi[r['tz']])]))

js = ('/* cities.js - generated by tools/build-cities.py. Do not edit by hand.\n'
      '   Data: GeoNames (geonames.org), cities15000, CC BY 4.0. %d places, sorted by population. */\n'
      'window.TD_CITIES = {tz:%s,\nadmin:%s,\nrows:%s};\n') % (
      len(out), json.dumps(tzs), json.dumps(admins, ensure_ascii=False), json.dumps('\n'.join(out), ensure_ascii=False))
dst = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'js', 'data', 'cities.js')
open(dst, 'w', encoding='utf-8').write(js)
print(len(out), 'rows,', len(tzs), 'time zones,', len(admins), 'regions,', os.path.getsize(dst), 'bytes')
